title: Modlists By Boneyard Creations
description: Boneyard Creations Modlist Wiki
theme: just-the-docs
color_scheme: dark-custom

url: https://themrnewvegas.github.io
favicon_ico: https://user-images.githubusercontent.com/112358568/227128385-9f7cc10c-8a71-4a81-9b3e-5fbca90043fd.png

search_enabled: true

search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

 # Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022 TheMrNewVegas"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

aux_links:
  "Patreon":
    - "https://www.patreon.com/Themrnewvegas"
  "Discord":
    - "https://discord.gg/43EhRjU"
  "Youtube":
    - "https://youtu.be/JE7h5ka_kwI"
  "Twitch":
    - "https://www.twitch.tv/TheMrNewVegas"    
  "Kofi":
    - "https://ko-fi.com/themrnewvegas" 

    # Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/TheMrNewVegas/TheMrNewVegas.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

nav_external_links:
  - title: Tale of Two Wastelands Website
    url: https://thebestoftimes.github.io
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: Download Wabbajack
    url: https://github.com/wabbajack-tools/wabbajack/releases/latest/download/Wabbajack.exe
    hide_icon: false # set to true to hide the external link icon - defaults to false    

callouts_level: loud
callouts:
  highlight:
    title: Notice
    color: yellow
  important:
    title: Important
    color: yellow
  logfile:
    title: Log Section
    color: green
  iniSetting:
    title: INI Setting
    color: green
  alternative:
    title: Alternative
    color: green
  console:
    title: Console Commands
    color: green    
  hint:
    title: Hint
    color: green  
  note:
    title: Note
    color: yellow
  warning:
    title: Warning
    color: red
  NoTitleYellow:
    color: yellow
  NoTitleGreen:
    color: green
    
# Define Jekyll collections
collections:
  01CapitalPunishment:
    permalink: "/:collection/:path/"
    output: true
  02ForlornHope:
    permalink: "/:collection/:path/"
    output: true
  03LostRune:
    permalink: "/:collection/:path/"
    output: true
  04Nostalgia:
    permalink: "/:collection/:path/"
    output: true
     
just_the_docs:
  collections: 
   01CapitalPunishment:
      name: Capital Punishment - TTW
      nav_fold: true 
   02ForlornHope:
      name: Forlorn Hope - FO4
      nav_fold: true   
   03LostRune:
      name: Lost Rune - SK:AE
      nav_fold: true   
   04Nostalgia:
      name: Nostalgia - FNV
      nav_fold: true 
  
      
