title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://themrnewvegas.github.io

aux_links:
  Template Repository: https://https://github.com/TheMrNewVegas/TheMrNewVegas.github.io/
